version: '3.8'
services:
  api:
    image: hebrew-tutor/api:latest
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/hebrew_tutor
      - REDIS_URL=redis://redis:6379
      - MINIO_URL=minio:9000
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    depends_on:
      - postgres
      - redis
      - minio
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=hebrew_tutor
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
volumes:
  postgres_data:
  minio_data: